### ISSUE TITLE
Discussion: I've built something similar

### ISSUE THREAD

**Issue by flaviut** [stephtr/qalculator#22]
Hey, I've built something similar at https://flaviutamas.com/qalculate-wasm/, https://github.com/flaviut/qalculate-wasm. Biggest difference is that it uses a makefile to automate and make reproducible the build process, and that @coolreader18 has contributed gnuplot support.

Just thought you might want to know, since some of the code may be useful. Your project is definitely the more polished one, I now have it bookmarked instead.

**Comment by stephtr** [comment]
Hey,

Thanks for your note! I actually already previously stumbled across your project. Especially the gnuplot support is really cool and it's definitely on my to do list. Just a matter of when I find enough time to do it.

**Comment by stephtr** [comment]
I actually improved the build system to provide a docker image, which contains everything for the build process, see https://github.com/stephtr/libqalculate-wasm Documentation should be following in the coming days.

Your code helped me to optimize the build process on a few edges. I also learned how to get some plotting functionality. For a quick prototype, I actually coupled libqalculate with Chart.JS instead of gnuplot. See https://v2.qalculator.pages.dev/
