### ISSUE TITLE
kWh unit doesn't work

### ISSUE THREAD

**Issue by oxan** [stephtr/qalculator#23]
Qalculator doesn't know the `kWh` unit, while it works fine in `qalc` and qalculate-gtk. If I try to use it, I get the error message "kWh is not a valid variable/function/unit". Defining `kWh := kW*h` in the additional settings is an easy workaround, but I'm mostly intrigued why Qalculator.xyz behaves differently from the desktop version here.

**Comment by stephtr** [comment]
Hi,
The reason why it behaves differently is because implicit multiplications are switched off by default in Qalculator. If you switch them off in qalculate, you will receive the same result.
Since in my opinion units like `kWh` should be available by default, I'll make a change (and add an additional toggle in the settings).

**Comment by stephtr** [comment]
Fixed by 2cdab5c. When opening Qalculator, it might take a few moments until it starts updating.

**Comment by oxan** [comment]
Thank you!
