### ISSUE TITLE
Exchange rates update

### ISSUE THREAD

**Issue by ferenczy** [stephtr/qalculator#25]
Is there any way to update exchange rates, please? When I use the exchange rate conversion feature (e.g. `1 EUR to USD`) I get a result with the following error message: 

> It has been 19914 day since the exchange rates
last were updated.

Apart from the broken English (but it's a problem of the `libqalculate` library, I guess), the application (library) is using outdated exchange rates.

The desktop application Qalculate has a menu item that triggers the exchange rates update and the application is also updating them periodically, if I remember correctly.

**Comment by stephtr** [comment]
Sorry, it took a while.
I just reworked the way the exchange rates are cached in [d0708e8](https://github.com/stephtr/qalculator/commit/d0708e8137dfdf12f4a7977a78f849d3af34be6f#diff-0bd27c5c251a83cb69764766b3e006e1d32b8c3890ea38e869dc09783b9a6509).
The exchange rate should be cached. Each time Qalculator gets opened, it updates exchange rates (if available).

Due to a bug in the code, up until now Qalculator was falling back to older exchange rates while being offline. But I don't see how this could lead to libqalculate throwing this error message.

I hope, that the error message doesn't arise after today's update (leave the app open for 10-20 s, while it downloads the update in the background). If the error message is still there, just let me know.
